name: Build and deploy ASP app to Azure Web App - BookNeT

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # שלב 1: Checkout את הקוד שלך
      - uses: actions/checkout@v4

      # שלב 2: Setup MSBuild path
      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2

      # שלב 3: Setup NuGet
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      # שלב 4: Restore NuGet packages (נכון אם יש לך קובץ packages.config, אחרת נוכל להחליף ב-docker restore)
      - name: Restore NuGet packages
        run: nuget restore

      # שלב 5: אם מדובר בפרויקט .NET, יש להוסיף את dotnet restore כדי לשחזר תלויות
      - name: Restore dependencies
        run: dotnet restore ./BookNeT.sln  # אם יש לך קובץ Solution בשם BookNeT.sln

      # שלב 6: Build את הפרויקט
      - name: Build the project
        run: dotnet build ./BookNeT.sln --configuration Release

      # שלב 7: Publish את הפרויקט לקובץ פיזי
      - name: Publish to folder
        run: msbuild /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="\published\" 

      # שלב 8: Upload artifact
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: ASP-app
          path: '/published/**'

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      # שלב 1: Download artifact מהשלב הקודם
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: ASP-app

      # שלב 2: Deploy ל-Azure Web App
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'BookNeT'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_698BC021C69048628DF1BC8B9E7049E4 }}
          package: .
